<?php
// Template
/*
[
    'label' => __(''),
    'icon' => null,
    'identifier' => '',
    'href' => '#',
    'ability' => null,
    'children' => [],
],
*/
return [
    [
        'label' => __('CRM'),
        'icon' => null,
        'identifier' => 'crm',
        'href' => '#',
        'ability' => null,
        'children' => [
            [
                'label' => __('Clients'),
                'icon' => null,
                'identifier' => 'clients',
                'href' => route('dashboard.admin.crm.client.index'),
                'ability' => null,
                'children' => [],
            ],
            [
                'label' => __('Ticket Categories'),
                'icon' => null,
                'identifier' => 'ticket-category',
                'href' => route('dashboard.admin.crm.ticket-category.index'),
                'ability' => null,
                'children' => [],
            ],
            [
                'label' => __('Support Tickets'),
                'icon' => null,
                'identifier' => 'ticket',
                'href' => route('dashboard.admin.crm.ticket.index'),
                'ability' => null,
                'children' => [],
            ],
        ],
    ],
    [
        'label' => __('Sold Items'),
        'icon' => null,
        'identifier' => '',
        'href' => '#',
        'ability' => null,
        'children' => [
            [
                'label' => __('Boxes'),
                'icon' => null,
                'identifier' => '',
                'href' => '#',
                'ability' => null,
                'children' => [],
            ],
            [
                'label' => __('Products'),
                'icon' => null,
                'identifier' => '',
                'href' => '#',
                'ability' => null,
                'children' => [],
            ],
            [
                'label' => __('Services'),
                'icon' => null,
                'identifier' => '',
                'href' => '#',
                'ability' => null,
                'children' => [],
            ],
        ],
    ],
    [
        'label' => __('Catalog'),
        'icon' => null,
        'identifier' => 'catalog',
        'href' => '#',
        'ability' => null,
        'children' => [
            [
                'label' => __('Box Types'),
                'icon' => null,
                'identifier' => config('nova.box_category_code') . '-category',
                'href' => route('dashboard.admin.catalog.product-type.index', ['category_code' => config('nova.box_category_code')]),
                'ability' => null,
                'children' => [],
            ],
            [
                'label' => __('Categories'),
                'icon' => null,
                'identifier' => 'product-categories',
                'href' => route('dashboard.admin.catalog.product-category.index'),
                'ability' => null,
                'children' => [],
            ],
            [
                'label' => __('Product Types'),
                'icon' => null,
                'identifier' => ['any-product-category', '-category'],
                'href' => route('dashboard.admin.catalog.product-type.index'),
                'ability' => null,
                'children' => [],
            ],
            [
                'label' => __('Service Types'),
                'icon' => null,
                'identifier' => config('nova.box_service_category_code') . '-category',
                'href' => route('dashboard.admin.catalog.product-type.index', ['category_code' => config('nova.box_service_category_code')]),
                'ability' => null,
                'children' => [],
            ],
            [
                'label' => __('Suppliers'),
                'icon' => null,
                'identifier' => 'suppliers',
                'href' => route('dashboard.admin.catalog.supplier.index'),
                'ability' => null,
                'children' => [],
            ],
        ],
    ],
    [
        'label' => __('Sales'),
        'icon' => null,
        'identifier' => '',
        'href' => '#',
        'ability' => null,
        'children' => [
            [
                'label' => __('Invoices'),
                'icon' => null,
                'identifier' => '',
                'href' => '#',
                'ability' => null,
                'children' => [],
            ],
            [
                'label' => __('Orders'),
                'icon' => null,
                'identifier' => '',
                'href' => '#',
                'ability' => null,
                'children' => [],
            ],
            [
                'label' => __('Payments'),
                'icon' => null,
                'identifier' => '',
                'href' => '#',
                'ability' => null,
                'children' => [],
            ],
        ],
    ],
    [
        'label' => __('CMS'),
        'icon' => null,
        'identifier' => 'cms',
        'href' => '#',
        'ability' => null,
        'children' => [
            [
                'label' => __('Categories'),
                'icon' => null,
                'identifier' => 'post-categories',
                'href' => route('dashboard.admin.cms.post-category.index'),
                'ability' => null,
                'children' => [],
            ],
            [
                'label' => __('Gallery'),
                'icon' => null,
                'identifier' => 'gallery',
                'href' => route('dashboard.admin.gallery.index'),
                'ability' => null,
                'children' => [],
            ],
            [
                'label' => __('Posts'),
                'icon' => null,
                'identifier' => 'posts',
                'href' => route('dashboard.admin.cms.post.index'),
                'ability' => null,
                'children' => [],
            ],
            [
                'label' => __('Urls'),
                'icon' => null,
                'identifier' => 'custom-urls',
                'href' => route('dashboard.admin.cms.custom-url.index'),
                'ability' => null,
                'children' => [],
            ],
        ],
    ],
];